---
abstract: 'Generate personalized HTML from PODs.'
author:
  - 'Graciliano M. P. <gm@virtuasites.com.br>, Geoffrey Leach <gleach@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-HtmlEasy
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  English: 0
  Exporter::Easy: 0.16
  File::Slurp: 9999.13
  IPC::Run: 0.8
  Pod::Escapes: 1.04
  Pod::ParseLink: 1.06
  Pod::Parser: 0
  Readonly: 1.03
  Regexp::Common: 2.12
  Regexp::Common::Email::Address: 1.01
  Test::More: 0.94
  feature: 1.16
  version: 0.82
version: v1.1.10
